server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: utf-8
cloud:
  aws:
    s3:
      bucket: junior-test-bucket
    credentials:
      accessKey: sdhjshdk
      secretKey: dfjdkfj
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  h2:
    console:
      enabled: 'true'
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: 4oCYc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWhhbmdoYWUtYXNzaWdubWVudC1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2VjcmV0LWtleeKAmQo=
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
